window.TEST_SCHEDULE_DATA = [
  {
    "no": 1,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "ლექცია",
    "duration": 1,
    "day": "ორშაბათი",
    "start": "09:00",
    "finish": "10:00",
    "students": 68,
    "group": "MDEF25-4,MDEF25-5,MDEF25-6",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 2,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "ლექცია",
    "duration": 1,
    "day": "სამშაბათი",
    "start": "09:00",
    "finish": "10:00",
    "students": 66,
    "group": "MDEF25-1,MDEF25-2,MDEF25-3",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 3,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "სამშაბათი",
    "start": "12:00",
    "finish": "14:00",
    "students": 22,
    "group": "MDEF25-1",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 4,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "13:00",
    "finish": "15:00",
    "students": 22,
    "group": "MDEF25-2",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 5,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "15:00",
    "finish": "17:00",
    "students": 22,
    "group": "MDEF25-3",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 6,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "სამშაბათი",
    "start": "14:00",
    "finish": "16:00",
    "students": 22,
    "group": "MDEF25-4",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 7,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "სამშაბათი",
    "start": "10:00",
    "finish": "12:00",
    "students": 23,
    "group": "MDEF25-6",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 8,
    "semester": "2",
    "professor": "გიორგი გაგუა",
    "lecturerId": "643",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3145",
    "subject": "ფიზიოლოგია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "11:00",
    "finish": "13:00",
    "students": 23,
    "group": "MDEF25-5",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 9,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "12:00",
    "finish": "13:00",
    "students": 20,
    "group": "MDES26-1",
    "weeks": "1-15",
    "room": "707"
  },
  {
    "no": 10,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "13:00",
    "finish": "14:00",
    "students": 20,
    "group": "MDES26-2",
    "weeks": "",
    "room": "707"
  },
  {
    "no": 11,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "14:00",
    "finish": "15:00",
    "students": 20,
    "group": "MDES26-3",
    "weeks": "",
    "room": "707"
  },
  {
    "no": 12,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "15:00",
    "finish": "16:00",
    "students": 20,
    "group": "MDES26-4",
    "weeks": "",
    "room": "707"
  },
  {
    "no": 13,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "16:00",
    "finish": "17:00",
    "students": 20,
    "group": "MDES26-5",
    "weeks": "",
    "room": "707"
  },
  {
    "no": 14,
    "semester": "1",
    "professor": "ქეთევან ხვთისავრიშვილი",
    "lecturerId": "825",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "2266",
    "subject": "აკადემიური წერა",
    "category": "ლექცია",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "11:00",
    "finish": "12:00",
    "students": 100,
    "group": "MDES26-1,MDES26-2,MDES26-3,MDES26-4,MDES26-5,",
    "weeks": "",
    "room": "302"
  },
  {
    "no": 15,
    "semester": "1",
    "professor": "მატრონა ჩაჩუა",
    "lecturerId": "475",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "ლექცია",
    "duration": 1,
    "day": "პარასკევი",
    "start": "11:00",
    "finish": "12:00",
    "students": 100,
    "group": "MDES26-1,MDES26-2,MDES26-3,MDES26-4,MDES26-5",
    "weeks": "",
    "room": "702"
  },
  {
    "no": 16,
    "semester": "1",
    "professor": "ეკატერინე მიქაუტაძე",
    "lecturerId": "889",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "11:00",
    "finish": "13:00",
    "students": 20,
    "group": "MDES26-1",
    "weeks": "",
    "room": "706"
  },
  {
    "no": 17,
    "semester": "1",
    "professor": "ეკატერინე მიქაუტაძე",
    "lecturerId": "889",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "15:00",
    "finish": "17:00",
    "students": 20,
    "group": "MDES26-2",
    "weeks": "",
    "room": "706"
  },
  {
    "no": 18,
    "semester": "1",
    "professor": "კახა კალმახელიძე",
    "lecturerId": "915",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ხუთშაბათი",
    "start": "12:00",
    "finish": "14:00",
    "students": 20,
    "group": "MDES26-3",
    "weeks": "",
    "room": "308"
  },
  {
    "no": 19,
    "semester": "1",
    "professor": "კახა კალმახელიძე",
    "lecturerId": "915",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ხუთშაბათი",
    "start": "09:00",
    "finish": "11:00",
    "students": 20,
    "group": "MDES26-4",
    "weeks": "",
    "room": "304"
  },
  {
    "no": 20,
    "semester": "1",
    "professor": "ეკატერინე მიქაუტაძე",
    "lecturerId": "889",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3140",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "13:00",
    "finish": "15:00",
    "students": 20,
    "group": "MDES26-5",
    "weeks": "",
    "room": "706"
  },
  {
    "no": 21,
    "semester": "1",
    "professor": "ამირან ზაჰედი",
    "lecturerId": "1084",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "ლექცია",
    "duration": 1,
    "day": "ორშაბათი",
    "start": "10:00",
    "finish": "11:00",
    "students": 100,
    "group": "MDES26-1,MDES26-2,MDES26-3,MDES26-4,MDES26-5",
    "weeks": "",
    "room": "302"
  },
  {
    "no": 22,
    "semester": "1",
    "professor": "ალეკო ბაირამოვი",
    "lecturerId": "794",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "შაბათი",
    "start": "11:00",
    "finish": "13:00",
    "students": 20,
    "group": "MDES26-1",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 23,
    "semester": "1",
    "professor": "ალეკო ბაირამოვი",
    "lecturerId": "794",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "10:00",
    "finish": "12:00",
    "students": 20,
    "group": "MDES26-2",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 24,
    "semester": "1",
    "professor": "ალეკო ბაირამოვი",
    "lecturerId": "794",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "10:00",
    "finish": "12:00",
    "students": 20,
    "group": "MDES26-3",
    "weeks": "",
    "room": "706"
  },
  {
    "no": 25,
    "semester": "1",
    "professor": "ალეკო ბაირამოვი",
    "lecturerId": "794",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "შაბათი",
    "start": "15:00",
    "finish": "17:00",
    "students": 20,
    "group": "MDES26-4",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 26,
    "semester": "1",
    "professor": "ალეკო ბაირამოვი",
    "lecturerId": "794",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3119",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "შაბათი",
    "start": "17:00",
    "finish": "19:00",
    "students": 20,
    "group": "MDES26-5",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 27,
    "semester": "3",
    "professor": "მატრონა ჩაჩუა",
    "lecturerId": "475",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3163",
    "subject": "ბიოქიმია",
    "category": "ლექცია",
    "duration": 1,
    "day": "ორშაბათი",
    "start": "10:00",
    "finish": "11:00",
    "students": 47,
    "group": "MDES25-1,MDES25-2",
    "weeks": "",
    "room": "305"
  },
  {
    "no": 28,
    "semester": "3",
    "professor": "კახა კალმახელიძე",
    "lecturerId": "915",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3163",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "პარასკევი",
    "start": "10:00",
    "finish": "12:00",
    "students": 24,
    "group": "MDES25-1",
    "weeks": "",
    "room": "304"
  },
  {
    "no": 29,
    "semester": "3",
    "professor": "ნიკოლოზ ნონიკაშვილი",
    "lecturerId": "862",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3163",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ხუთშაბათი",
    "start": "17:00",
    "finish": "19:00",
    "students": 23,
    "group": "MDES25-2",
    "weeks": "",
    "room": "303"
  },
  {
    "no": 30,
    "semester": "3",
    "professor": "ნინო ფირცხელანი",
    "lecturerId": "508",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3164",
    "subject": "გენეტიკა",
    "category": "ლექცია",
    "duration": 1,
    "day": "ორშაბათი",
    "start": "13:00",
    "finish": "14:00",
    "students": 47,
    "group": "MDES25-1,MDES25-2",
    "weeks": "",
    "room": "302"
  },
  {
    "no": 31,
    "semester": "3",
    "professor": "სიავაშ ჰოსეინპორ ჩერმაჰინი",
    "lecturerId": "890",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3164",
    "subject": "გენეტიკა",
    "category": "სემინარი",
    "duration": 2,
    "day": "შაბათი",
    "start": "10:00",
    "finish": "12:00",
    "students": 24,
    "group": "MDES25-1",
    "weeks": "",
    "room": "304"
  },
  {
    "no": 32,
    "semester": "3",
    "professor": "სიავაშ ჰოსეინპორ ჩერმაჰინი",
    "lecturerId": "890",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3164",
    "subject": "გენეტიკა",
    "category": "სემინარი",
    "duration": 2,
    "day": "შაბათი",
    "start": "12:00",
    "finish": "14:00",
    "students": 23,
    "group": "MDES25-2",
    "weeks": "",
    "room": "304"
  },
  {
    "no": 33,
    "semester": "3",
    "professor": "მარიამ ხარაიშვილი",
    "lecturerId": "505",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3165",
    "subject": "ბიოეთიკა",
    "category": "ლექცია",
    "duration": 1,
    "day": "პარასკევი",
    "start": "17:00",
    "finish": "18:00",
    "students": 46,
    "group": "MDES25-1,MDES25-2",
    "weeks": "",
    "room": "703"
  },
  {
    "no": 34,
    "semester": "3",
    "professor": "მარიამ ხარაიშვილი",
    "lecturerId": "505",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3165",
    "subject": "ბიოეთიკა",
    "category": "სემინარი",
    "duration": 1,
    "day": "პარასკევი",
    "start": "15:00",
    "finish": "16:00",
    "students": 24,
    "group": "MDES25-1",
    "weeks": "",
    "room": "703"
  },
  {
    "no": 35,
    "semester": "3",
    "professor": "მარიამ ხარაიშვილი",
    "lecturerId": "505",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3165",
    "subject": "ბიოეთიკა",
    "category": "სემინარი",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "13:00",
    "finish": "14:00",
    "students": 22,
    "group": "MDES25-2",
    "weeks": "",
    "room": "708"
  },
  {
    "no": 36,
    "semester": "3",
    "professor": "თამარ მგელაძე",
    "lecturerId": "507",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3158",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "სამშაბათი",
    "start": "10:00",
    "finish": "12:00",
    "students": 24,
    "group": "MDES25-1",
    "weeks": "",
    "room": "704"
  },
  {
    "no": 37,
    "semester": "3",
    "professor": "თამარ მგელაძე",
    "lecturerId": "507",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3158",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "სამშაბათი",
    "start": "14:00",
    "finish": "16:00",
    "students": 23,
    "group": "MDES25-2",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 38,
    "semester": "3",
    "professor": "თამარ მგელაძე",
    "lecturerId": "507",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "მედიცინა ინგლისურენოვანი",
    "courseId": "3158",
    "subject": "ანატომია",
    "category": "ლექცია",
    "duration": 1,
    "day": "სამშაბათი",
    "start": "09:00",
    "finish": "10:00",
    "students": 70,
    "group": "MDES25-1,MDES25-2,MDEF24-8",
    "weeks": "",
    "room": "710"
  },
  {
    "no": 39,
    "semester": "1",
    "professor": "ამირან ზაჰედი",
    "lecturerId": "1084",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3222",
    "subject": "ანატომია",
    "category": "ლექცია",
    "duration": 1,
    "day": "ხუთშაბათი",
    "start": "09:00",
    "finish": "10:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "704"
  },
  {
    "no": 40,
    "semester": "1",
    "professor": "ამირან ზაჰედი",
    "lecturerId": "1084",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3222",
    "subject": "ანატომია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ხუთშაბათი",
    "start": "11:00",
    "finish": "13:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "402"
  },
  {
    "no": 41,
    "semester": "1",
    "professor": "ანა აბესაძე",
    "lecturerId": "800",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3228",
    "subject": "ბიოქიმია",
    "category": "ლექცია",
    "duration": 1,
    "day": "ორშაბათი",
    "start": "10:00",
    "finish": "11:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "604"
  },
  {
    "no": 42,
    "semester": "1",
    "professor": "ანა აბესაძე",
    "lecturerId": "800",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3228",
    "subject": "ბიოქიმია",
    "category": "სემინარი",
    "duration": 2,
    "day": "ორშაბათი",
    "start": "11:00",
    "finish": "13:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "604"
  },
  {
    "no": 43,
    "semester": "1",
    "professor": "მადონა გიორგაძე",
    "lecturerId": "681",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3233",
    "subject": "აკადემიური წერა",
    "category": "ლექცია",
    "duration": 1,
    "day": "შაბათი",
    "start": "10:00",
    "finish": "11:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "702"
  },
  {
    "no": 44,
    "semester": "1",
    "professor": "მადონა გიორგაძე",
    "lecturerId": "681",
    "school": "მედიცინის საერთაშორისო სკოლა",
    "program": "სტომატოლოგია",
    "courseId": "3233",
    "subject": "აკადემიური წერა",
    "category": "სემინარი",
    "duration": 1,
    "day": "შაბათი",
    "start": "11:00",
    "finish": "12:00",
    "students": 20,
    "group": "DENS26",
    "weeks": "",
    "room": "702"
  }
];

